import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConversationContextProvider from "@/context/ConversationContext";
import Sidebar from "../components/ui/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        <Sidebar />
        <ConversationContextProvider>
          <main className="flex-1 p-6 overflow-y-auto">{children}</main>
        </ConversationContextProvider>
      </body>
    </html>
  );
}
